      SUBROUTINE ADAJ(NC,JDT,M,I,NYD)
!     EPIC1102
!     THIS SUBPROGRAM COMPUTES THE DAY OF THE YEAR, GIVEN THE MONTH AND
!     THE DAY OF THE MONTH.
      DIMENSION NC(13)
      JDT=NC(M)+I
      IF(M>2)JDT=JDT-NYD
	  RETURN
      END