      FUNCTION ADSTN(RN1,RN2)
!     EPIC1102
!     THIS SUBPROGRAM COMPUTES A STANDARD NORMAL DEVIATE GIVEN TWO RANDOM
!     NUMBERS
      ADSTN=SQRT(-2.*LOG(RN1))*COS(6.283185*RN2)
      RETURN
      END