      SUBROUTINE CCONI
!     THIS SUBPROGRAM DOES AN INITIAL PARTITION EACH GAS CONC. IN AIR 
!     INTO GAS CONCENTRATION IN AIR AND LIQUID PHASE AND THEN
!     CALCULATES THE TOTAL GAS CONCENTRATION (G/M3 SOIL)
!     IT IS AN APPROXIMATION AND SHOULD BE CALCULATED ONLY ONCE AT THE
!     BEGINNING OF EACH SIMULATION - RCI - 7/19/09
      USE PARM                                                                       
      DO J=1,NBCL
	      CLO2(J)=CGO2(J)/HKPO(J)	
	      CLCO2(J)=CGCO2(J)/HKPC(J)
	      CLN2O(J)=CGN2O(J)/HKPN(J)	
	      AO2C(J)=CGO2(J)*AFP(J)+CLO2(J)*VWC(J)
	      ACO2C(J)=CGCO2(J)*AFP(J)+CLCO2(J)*VWC(J)
	      AN2OC(J)=CGN2O(J)*AFP(J)+CLN2O(J)*VWC(J)
	  END DO
      RETURN
      END