      SUBROUTINE CFRG(I,J,F,RGS,X,JRT)
!     EPIC1102
!     DETERMINES MINIMUM STRESS FACTORS FOR ROOT AND TOTAL BIOMASS
!     GROWTH.
      USE PARM
      JRT=0
      IF(F>=RGS)RETURN
      RGS=MAX(0.,F)
      J=I
      IF(RGS<=X)JRT=1
      RETURN
      END