      SUBROUTINE ESLOS(JRT)
!     EPIC1102
!     THIS SUBPROGRAM CALCULATES THE THICKNESS OF SOIL REMOVED BY EACH
!     EROSION EVENT, MOVES THE TOP LAYER INTO THE SECOND LAYER BY A DIST
!     EQUAL THE ERODED THICKNESS, AND ADJUSTS THE TOP LAYER SOIL
!     PROPERTIES BY INTERPOLATION.  WHEN THE SECOND LAYER IS REDUCED TO
!     TO A THICKNESS OF 10 MM, IT IS PLACED INTO THE THIRD LAYER.
      USE PARM
      WFN(X1,X2,Z1,Z2,ZZ)=(Z1*X1+Z2*X2)/ZZ
      TK=.1*YERO/BD(LD1)
	  THK=THK+TK
      TK=MIN(TK*.001,Z(LD1))
      J=LID(NBSL)
      W1=Z(LD1)-TK
      W2=TK
      WT(LD1)=WT(LD1)-YERO
      IF(Z(LID(2))-Z(LD1)-TK>.01)GO TO 10
!     REMOVE LAYER 2 AND PLACE SMALL REMAINING CONTENTS IN LAYER 3
      ISL=LID(3)
      LD2=LID(2)
      Z1=Z(LD2)-Z(LD1)
      Z2=Z(ISL)-Z(LD2)
      VV=Z1+Z2
      ZZ=.01/VV
      PSP(ISL)=WFN(PSP(LD2),PSP(ISL),Z1,Z2,VV)
      BDM(ISL)=WFN(BDM(LD2),BDM(ISL),Z1,Z2,VV)
      CLA(ISL)=WFN(CLA(LD2),CLA(ISL),Z1,Z2,VV)
      SIL(ISL)=WFN(SIL(LD2),SIL(ISL),Z1,Z2,VV)
      SAN(ISL)=100.-CLA(ISL)-SIL(ISL)
      ROK(ISL)=WFN(ROK(LD2),ROK(ISL),Z1,Z2,VV)
      SATC(ISL)=WFN(SATC(LD2),SATC(ISL),Z1,Z2,VV)
      PH(ISL)=WFN(PH(LD2),PH(ISL),Z1,Z2,VV)
      WT(ISL)=WT(ISL)+WT(LD2)
      BD(ISL)=.0001*WT(ISL)/VV
      WNO3(ISL)=WNO3(ISL)+WNO3(LD2)
      WHPN(ISL)=WHPN(ISL)+WHPN(LD2)
      WHSN(ISL)=WHSN(ISL)+WHSN(LD2)
      WBMN(ISL)=WBMN(ISL)+WBMN(LD2)
      WLSN(ISL)=WLSN(ISL)+WLSN(LD2)
      WLMN(ISL)=WLMN(ISL)+WLMN(LD2)
      WHPC(ISL)=WHPC(ISL)+WHPC(LD2)
      WHSC(ISL)=WHSC(ISL)+WHSC(LD2)
      WBMC(ISL)=WBMC(ISL)+WBMC(LD2)
      WLS(ISL)=WLS(ISL)+WLS(LD2)
      WLM(ISL)=WLM(ISL)+WLM(LD2)
      WLSL(ISL)=WLSL(ISL)+WLSL(LD2)
      WLSC(ISL)=WLSC(ISL)+WLSC(LD2)
      WLMC(ISL)=WLMC(ISL)+WLMC(LD2)
      WLSLC(ISL)=WLSLC(ISL)+WLSLC(LD2)
      WLSLNC(ISL)=WLSC(ISL)-WLSLC(ISL)
      WP(ISL)=WP(ISL)+WP(LD2)
      RSD(ISL)=.001*(WLS(ISL)+WLM(ISL))
      AP(ISL)=AP(ISL)+AP(LD2)
      PMN(ISL)=PMN(ISL)+PMN(LD2)
      FOP(ISL)=FOP(ISL)+FOP(LD2)
      OP(ISL)=OP(ISL)+OP(LD2)
      S15(ISL)=S15(ISL)+S15(LD2)
      FC(ISL)=FC(ISL)+FC(LD2)
      PO(ISL)=PO(ISL)+PO(LD2)
      CALL SPOFC(ISL)
      ST(ISL)=ST(ISL)+ST(LD2)
      LORG(LD1)=LORG(LD2)
!     SPLIT LAYER NEAREST SURFACE WITH THICKNESS > 0.15 M IN HALF
      ZMX=0.
      L1=LD1
      MXZ=LD2
      DO J=3,NBSL
          ISL=LID(J)
          ZZ=Z(ISL)-Z(L1)
          IF(ZZ>.15)THEN
              MXZ=J
              ZMX=ZZ
              GO TO 7
          END IF
          L1=ISL
          IF(ZZ<=ZMX+.01)CYCLE
          ZMX=ZZ
          MXZ=J
      END DO
      ISL=LID(MXZ)
      L1=LID(MXZ-1)
      IF(ZMX>ZQT)GO TO 7
      NBSL=NBSL-1
      IF(NBSL<=2)THEN
          JRT=1
          RETURN
      END IF
      DO J=2,NBSL
          LID(J)=LID(J+1)
      END DO
      GO TO 10
    7 MX1=MXZ-1
      IF(MX1>2)THEN
          DO J=2,MX1
              LID(J)=LID(J+1)
          END DO
      END IF
      LID(MX1)=LD2
      LORG(LD2)=LORG(LID(MXZ))
      CALL SPLA(ISL,L1,LD2,1,.5)
!     ADJUST LAYER 1 BY INTERPOLATING BETWEEN LAYER 2 USING ERODED THICK
   10 ISL=LID(2)
      PSP(LD1)=WFN(PSP(LD1),PSP(ISL),W1,W2,Z(LD1))
      BDM(LD1)=WFN(BDM(LD1),BDM(ISL),W1,W2,Z(LD1))
      CLA(LD1)=WFN(CLA(LD1),CLA(ISL),W1,W2,Z(LD1))
      SIL(LD1)=WFN(SIL(LD1),SIL(ISL),W1,W2,Z(LD1))
      SAN(LD1)=100.-CLA(LD1)-SIL(LD1)
      BD(LD1)=WFN(BD(LD1),BD(ISL),W1,W2,Z(LD1))
      SATC(LD1)=WFN(SATC(LD1),SATC(ISL),W1,W2,Z(LD1))
!     HCL(LD1)=SATC(LD1)*UPS
      PH(LD1)=WFN(PH(LD1),PH(ISL),W1,W2,Z(LD1))
      XX=Z(ISL)-Z(LD1)
      GX=XX-TK
      RTO=GX/XX
      RX=1.
      IF(ROK(LD1)>0.)THEN
          X3=ROK(LD1)
          ROK(LD1)=WFN(ROK(LD1),ROK(ISL),W1,W2,Z(LD1))
          RX=(100.-ROK(LD1))/(100.-X3)
      END IF
      W1=W1/Z(LD1)
      W2=W2/XX
      S15(LD1)=WFN(S15(LD1),S15(ISL),W1,W2,RX)
      FC(LD1)=WFN(FC(LD1),FC(ISL),W1,W2,RX)
      PO(ISL)=PO(ISL)*RTO
      S15(ISL)=S15(ISL)*RTO
      FC(ISL)=FC(ISL)*RTO
      CALL SPOFC(ISL)
      WT(ISL)=WT(ISL)*RTO
      PO(LD1)=WFN(PO(LD1),PO(ISL),W1,W2,RX)
      CALL SPOFC(LD1)
      WNO3(LD1)=WNO3(LD1)+EAJL(WNO3(ISL),W2)
      WHPN(LD1)=WHPN(LD1)+EAJL(WHPN(ISL),W2)
      WHSN(LD1)=WHSN(LD1)+EAJL(WHSN(ISL),W2)
      WBMN(LD1)=WBMN(LD1)+EAJL(WBMN(ISL),W2)
      WLSN(LD1)=WLSN(LD1)+EAJL(WLSN(ISL),W2)
      WLMN(LD1)=WLMN(LD1)+EAJL(WLMN(ISL),W2)
      WHPC(LD1)=WHPC(LD1)+EAJL(WHPC(ISL),W2)
      WHSC(LD1)=WHSC(LD1)+EAJL(WHSC(ISL),W2)
      WBMC(LD1)=WBMC(LD1)+EAJL(WBMC(ISL),W2)
      WLS(LD1)=WLS(LD1)+EAJL(WLS(ISL),W2)
      WLM(LD1)=WLM(LD1)+EAJL(WLM(ISL),W2)
      WLSL(LD1)=WLSL(LD1)+EAJL(WLSL(ISL),W2)
      WLSC(LD1)=WLSC(LD1)+EAJL(WLSC(ISL),W2)
      WLMC(LD1)=WLMC(LD1)+EAJL(WLMC(ISL),W2)
      WLSLC(LD1)=WLSLC(LD1)+EAJL(WLSLC(ISL),W2)
      WLSLNC(LD1)=WLSC(LD1)-WLSLC(LD1)
      WP(LD1)=WP(LD1)+EAJL(WP(ISL),W2)
      RSD(LD1)=.001*(WLS(LD1)+WLM(LD1))
      AP(LD1)=AP(LD1)+EAJL(AP(ISL),W2)
      PMN(LD1)=PMN(LD1)+EAJL(PMN(ISL),W2)
      FOP(LD1)=FOP(LD1)+EAJL(FOP(ISL),W2)
      OP(LD1)=OP(LD1)+EAJL(OP(ISL),W2)
      SOLK(LD1)=SOLK(LD1)+EAJL(SOLK(ISL),W2)
      EXCK(LD1)=EXCK(LD1)+EAJL(EXCK(ISL),W2)
      FIXK(LD1)=FIXK(LD1)+EAJL(FIXK(ISL),W2)
      ST(LD1)=ST(LD1)+EAJL(ST(ISL),W2)
      XY=.01*(1.-.01*ROK(LD1))
      XX=XY
      WT(LD1)=BD(LD1)*100.
      ABD=WT(LD1)
      DO J=2,NBSL
          ISL=LID(J)
          Z(ISL)=Z(ISL)-TK
          ABD=ABD+WT(ISL)
      END DO
      XX=Z(LID(NBSL))
      IF(XX<=ZF)THEN
          JRT=1
          RETURN
      END IF
      IF(BIG>=XX)THEN
          BIG=XX
          PMX=XX
      END IF
      ABD=ABD*1.E-4/Z(LID(NBSL))
      NBCL=Z(LID(NBSL))/DZ+1.
      RETURN
      END