      SUBROUTINE EWER(JRT)
!     EPIC1102
!     THIS SUBPROGRAM ESTIMATES DAILY SOIL LOSS CAUSED BY WIND EROSION,
!     GIVEN THE AVERAGE WIND SPEED AND DIRECTION.
      USE PARM
      JRT=0
      IF(U10<PRMT(67))THEN
          JRT=1
          RETURN
      END IF
      BT=PI2/4.+TH-ANG
      ALG=FL*FW/(FL*ABS(COS(BT))+FW*ABS(SIN(BT)))
      RRF=11.9*(1.-EXP(-(RRUF/9.8)**1.3))
      RIF=ABS(SIN(BT))*(1.27*RHTT**.52)
      RFB=MAX(.1,RRF+RIF)
      RFC=.77*1.002**RHTT
      RGRF=1.
      X1=(10./RFB)**RFC
      IF(X1<10.)RGRF=1.-EXP(-X1)
	  X1=VAC
      X1=MIN(10.,X1+BWD(3,JD)*RSD(LD1))
      VF=1.-X1/(X1+EXP(SCRP(13,1)-SCRP(13,2)*X1))
      ALG=1.-EXP(-ALG/.07)
      RTO=ST(LD1)/S15(LD1)
      SMM(68,MO)=SMM(68,MO)+ST(LD1)
      VAR(68)=ST(LD1)
      NWDA=NWDA+1
      USTW=USTT+.5*RTO*RTO
      ROKF=EXP(-.047*ROK(LD1))
      CALL EWNINT
      WK1=WK*EXP(-.001*TLMF)
      SMM(38,MO)=SMM(38,MO)+WK1
      VAR(38)=WK1
      YW=8640.*YW*RGRF*VF*ROKF*WK1
      TLMF=TLMF+YW
      RETURN
      END