      SUBROUTINE EYCC
!     EPIC1102
!     THIS SUBPROGRAM ESTIMATES THE USLE C FACTOR BASED ON PLANT POP &
!     BIOMASS & RESIDUE COVER
      USE PARM
	  X1=MIN(10.,PRMT(60)*CV)
	  CVF=(.8*EXP(-X1)+CFMN)*(.9*(1.-CVP)+.1)
      CVF=CVF*EXP(-.05*ROK(LD1))
      RETURN
      END