	  SUBROUTINE GETCL(CM,KW)
!     THIS COMMAND LINE ROUTINE FOR MICROSOFT/UNIX/SALFORD
      CHARACTER*80 CM
      DIMENSION KW(200)
      DIMENSION CM(9)
      CM=' '
      NNARG=NARGS()
	  IF(NNARG>9)NNARG=9
      DO I=1,NNARG
          CALL GETARG(I-1,CM(I),NCHAR)
	  END DO
	  RETURN
      END