      FUNCTION HQP(X1,CQP,ITP,INT)
      DIMENSION CQP(8,17,4)
!     EPIC1102
      HQP=CQP(1,INT,ITP)+X1*(CQP(2,INT,ITP)+X1*(CQP(3,INT,ITP)+X1*&
     &(CQP(4,INT,ITP)+X1*(CQP(5,INT,ITP)+X1*(CQP(6,INT,ITP)+X1*&
     &(CQP(7,INT,ITP)+X1*CQP(8,INT,ITP)))))))
      RETURN
      END