      SUBROUTINE HRUNF
!     EPIC1102
!     THIS SUBPROGRAM DISTRIBUTES DAILY RAINFALL UNIFORMLY &
!     FURNISHES THE GREEN & AMPT SUBPROGRAM RAIN INCREMENTS OF EQUAL
!     VOLUME = DRFV
      USE PARM
      DATA DRFV/5./
      PT=0.
!      WRITE(KW(1),1)SCN,RFV,REP,DUR
      DO WHILE(PT<RFV)
          PT=PT+DRFV
          CALL HGASP(DRFV,PT,Q1,REP)
!          WRITE(KW(1),1)PT,QD
      END DO
      A=RFV-PT+DRFV
      PT=RFV
      CALL HGASP(A,PT,Q1,REP)
!      WRITE(KW(1),1)PT,QD
!      WRITE(KW(1),13)IYR,MO,KDA,SCN,RFV,PT,QD,REP,DUR   !skang
      RETURN
    1 FORMAT(1X,10E13.5)
   13 FORMAT(1X,3I4,10F10.2)
      END