      SUBROUTINE HSNOM
!     EPIC1102
!     THIS SUBPROGRAM PREDICTS DAILY SNOW MELT WHEN THE AVERAGE AIR
!     TEMPERATURE EXCEEDS 0 DEGREES C.
      USE PARM
      X2=MIN(DST0,STMP(LID(2)))
      X1=SQRT(TMX*SRAD)
      SNPKT=.3333*(2.*X2+TX)
      F=TSNO/(TSNO+EXP(SCRP(16,1)-SCRP(16,2)*TSNO))
      SML=MAX(0.,X1*(1.52+.54*F*SNPKT))
      SML=MIN(SML,SNO)
      SNO=SNO-SML
      IF(REP<1.E-5)REP=.042*SML
      PR=.042
      DUR=24.
      RETURN
      END