      SUBROUTINE HSWBL(P,Q,ET,SSF,O,RG,SNO,SW,SWW,QINT,RGDL,KW,MSO)
!     EPIC1102
!     THIS SUBPROGRAM CHECKS THE SOIL WATER BALANCE AT THE END OF A
!     SIMULATION.
      DIMENSION KW(MSO+3)
!      WRITE(KW(1),'(T10,A)')'SOIL WATER BALANCE'  !skang
      DF=SWW+P-Q-ET-O-SW-SSF+RG-SNO+QINT-RGDL
      PER=100.*DF/SW
!      WRITE(KW(1),1)PER,DF,SWW,P,Q,ET,O,SSF,RG,RGDL,SNO,QINT,SW
      SWW=SW+SNO
      RETURN    
    1 FORMAT(5X,'PER =',E13.6,2X,'DF  =',E13.6,2X,'BSW =',E13.6,2X,&
     &'PCP =',E13.6,2X,'Q   =',E13.6,2X,'ET  =',E13.6/5X,'PRK =',E13.6,&
     &2X,'SSF =',E13.6,2X,'IRG =',E13.6,2X,'IRDL=',E13.6,2X,'SNO =',&
     &E13.6,2X,'QIN =',E13.6,2X/5X,'FSW =',E13.6)
      END