      SUBROUTINE HSWU(CPWU,RGS)
!     EPIC1102
!     THIS SUBPROGRAM DISTRIBUTES PLANT EVAPORATION THROUGH THE ROOT
!     ZONE AND CALCULATES ACTUAL PLANT WATER USE BASED ON SOIL WATER
!     AVAILABILITY.
      USE PARM
      BLM=S15(ISL)
      IF(Z(ISL)<=.5)BLM=PRMT(5)*S15(ISL)
      IF(ISL/=LD1)THEN
          CALL CRGBD(RGS)
          CPWU=CPWU*RGS
      END IF
      SUM=EP(JJK)*(1.-EXP(-UB1*GX/RD(JJK)))/UOB
      TOS=36.*ECND(ISL)
      XX=LOG10(S15(ISL))
      WTN=MAX(5.,10.**(3.1761-1.6576*((LOG10(ST(ISL))-XX)/(LOG10(FC&
      (ISL))-XX))))
      XX=TOS+WTN
      IF(XX<5000.)THEN
          F=1.-XX/(XX+EXP(SCRP(21,1)-SCRP(21,2)*XX))
          U(ISL)=MIN(SUM-CPWU*SU-(1.-CPWU)*UX,ST(ISL)-BLM)*RGS*F
          IF(U(ISL)<0.)U(ISL)=0.
      END IF    
      UX=SUM
      RETURN
      END