      SUBROUTINE NCBL(BTC,YOC,VBC,QBC,RSPC,TFOC,PPCN,YLDC,BURN,FTC,KW,MSO)
!     EPIC1102
!     THIS SUBPROGRAM COMPUTES THE C BALANCE AT THE END OF THE
!     SIMULATION
      DIMENSION KW(MSO+3)
!      WRITE(KW(1),'(/T10,A)')'C BALANCE'
      DF=BTC-YOC-VBC-QBC-RSPC+TFOC+PPCN-BURN-YLDC-FTC
      PER=100.*DF/FTC
!      WRITE(KW(1),1)PER,DF,BTC,YOC,VBC,QBC,RSPC,TFOC,PPCN,YLDC,BURN,FTC
      BTC=FTC
      RETURN
    1 FORMAT(5X,'PER =',E13.6,2X,'DF  =',E13.6,2X,'BTOT=',E13.6,2X,&
      'Y   =',E13.6,2X,'PRK =',E13.6,2X,'Q   =',E13.6/5X,'RSPC=',E13.6,&
      2X,'TFOC=',E13.6,2X,'NPPC='E13.6,2X,'YLDC=',E13.6,2X,'BURN=',E13.6,&
      2X,'FTOT=',E13.6)
      END