      SUBROUTINE NDNITAK
!     EPIC1102
!     THIS SUBPROGRAM DEVELOPED BY ARMEN KEMANIAN ESTIMATES DAILY 
!     DENITRIFICATION AND N2O LOSSES OF SOIL NO3.
	  USE PARM
	  WDN=0.
	  DN2O=0.
!     COMPUTE WATER FACTOR
	  AIRV=MAX(0.,(PO(ISL)-ST(ISL))/DZA)
	  X1=0.90+.001*CLA(ISL)
	  X2=(1.0001-AIRV)/X1
	  IF(X2<.8)RETURN
	  H2O_F=1./(1.+X2**(-60))
!     COMPUTE NITRATE FACTOR
	  ONO3_C=MAX(1.E-5,1000.*WNO3(ISL)/WT(ISL))
 	  ONO3_F=ONO3_C/(ONO3_C+60.)
!     COMPUTE RESPIRATION FACTOR
	  X3=1000.*RSPC(ISL)/WT(ISL)
	  C_F=MIN(1.,X3/50.)
	  D_F=ONO3_F*H2O_F*C_F
	  DNITMX=32.
	  WDN=MIN(PRMT(30),D_F*DNITMX*WT(ISL)/1000.)
	  IF(WDN>WNO3(ISL))WDN=WNO3(ISL)
	  !compute N2O as a fraction of WDN
	  DN2O=ONO3_F*(1.-SQRT(H2O_F))*(1.-C_F**.25)*WDN
	  WNO3(ISL)=WNO3(ISL)-WDN
      RETURN
	  END