      SUBROUTINE NDNIT
!     EPIC1102
!     THIS SUBPROGRAM ESTIMATES DAILY LOSS OF NO3 BY DENITRIFICATION.
      USE PARM
      AIRV=MAX(0.,(PO(ISL)-ST(ISL))/DZA)
	  X1=0.90+.001*CLA(ISL)
	  X2=(1.0001-AIRV)/X1
	  IF(X2<.8)RETURN
	  F=1./(1.+X2**(-60))
      !F=X2/(X2+EXP(SCRP(25,1)-SCRP(25,2)*X2))
	  X1=MIN(PRMT(4),1.-EXP(-RSPC(ISL)/WT(ISL)))
      WDN=WNO3(ISL)*X1*F
	  IF(WDN>WNO3(ISL))WDN=WNO3(ISL)
      WNO3(ISL)=WNO3(ISL)-WDN
      DN2=PRMT(80)*WDN
      DN2O=WDN-DN2
      RETURN
      END