      SUBROUTINE NKMIN
!     EPIC1102
!     THIS SUBPROGRAM COMPUTES K FLUX BETWEEN THE WATER SOLUBLE,
!     EXCHANGEABLE, & FIXED POOLS
      USE PARM
      RSE=(SOLK(ISL)-EXCK(ISL)*EQKS(ISL))*PRMT(29)
      REF=(EXCK(ISL)-FIXK(ISL)*EQKE(ISL))*PRMT(22)
      SOLK(ISL)=MAX(.0001,SOLK(ISL)-RSE)
      EXCK(ISL)=MAX(.0001,EXCK(ISL)+RSE-REF)
      FIXK(ISL)=FIXK(ISL)+REF
      RETURN
      END