      SUBROUTINE NLGB(WTI,WTO,WTB,WTE,KW,MSO)
!     EPIC1102
!     THIS SUBPROGRAM THE LAGOON MANURE BALANCE
      DIMENSION KW(MSO+3)
      DF=WTB+WTI-WTO-WTE
      PER=200.*DF/(WTB+WTE)
!      WRITE(KW(1),2)
!      WRITE(KW(1),1)PER,DF,WTB,WTI,WTO,WTE     
      RETURN
    1 FORMAT(5X,'PER =',E13.6,2X,'DF  =',E13.6,2X,'WTB =',E13.6,2X,&
     &'WTI =',E13.6,2X,'WTO =',E13.6,2X,'WTE =',E13.6)
    2 FORMAT(T10,'LAGOON MANURE BALANCE')
      END