      SUBROUTINE NPMIN
!     EPIC1102
!     THIS SUBPROGRAM COMPUTES P FLUX BETWEEN THE LABILE, ACTIVE MINERAL
!     AND STABLE MINERAL P POOLS.
!     S5=.1*SUT(ISL)*EXP(.115*STMP(ISL)-2.88)
      USE PARM
      RTO=MIN(.8,PSP(ISL)/(1.-PSP(ISL)))
      RMN=PRMT(77)*(AP(ISL)-PMN(ISL)*RTO)
      X1=4.*PMN(ISL)-OP(ISL)
      IF(X1>500.)THEN
          ROC=10.**(LOG10(BPC(ISL))+LOG10(X1))
      ELSE
          ROC=BPC(ISL)*X1
      END IF
      ROC=PRMT(78)*ROC
      OP(ISL)=OP(ISL)+ROC
      PMN(ISL)=PMN(ISL)-ROC+RMN
      AP(ISL)=AP(ISL)-RMN
      RETURN
      END