      SUBROUTINE NPUP
!     EPIC1102
!     THIS SUBPROGRAM CALCULATES THE DAILY P DEMAND FOR OPTIMAL PLANT
!     GROWTH.
      USE PARM
	  IF(NUPC==0)THEN
	      CPT=BP(2,JJK)+BP(1,JJK)*EXP(-BP(4,JJK)*HUI(JJK))
	  ELSE
          CPT=(BP(4,JJK)-BP(3,JJK))*(1.-HUI(JJK)/(HUI(JJK)+EXP(BP(1,JJK)-&
          &BP(2,JJK)*HUI(JJK))))+BP(3,JJK)
      END IF
	  UP2(JJK)=CPT*DM(JJK)*1000.
      UPP=MIN(4000.*BP(3,JJK)*DDM(JJK),UP2(JJK)-UP1(JJK))
      UPP=MAX(0.,UPP)
      RETURN
      END