      SUBROUTINE NUK
!     EPIC1102
!     THIS SUBPROGRAM CALCULATES THE DAILY K DEMAND FOR OPTIMAL PLANT
!     GROWTH.
      USE PARM
      CKT=BK(1,JJK)+HUI(JJK)*(BK(2,JJK)+HUI(JJK)*BK(4,JJK))
      UK2(JJK)=CKT*DM(JJK)*1000.
      IF(UK2(JJK)<UK1(JJK))UK2(JJK)=UK1(JJK)
      UPK=MIN(4000.*BK(3,JJK)*DDM(JJK),UK2(JJK)-UK1(JJK))
      RETURN
      END