      SUBROUTINE NUP
!     EPIC1102
!     THIS SUBPROGRAM CALCULATES THE DAILY N DEMAND FOR OPTIMAL PLANT
!     GROWTH.
      USE PARM
	  IF(NUPC==0)THEN
          CNT=BN(2,JJK)+BN(1,JJK)*EXP(-BN(4,JJK)*HUI(JJK))
	  ELSE
          CNT=(BN(4,JJK)-BN(3,JJK))*(1.-HUI(JJK)/(HUI(JJK)+EXP(BN(1,JJK)-&
          &BN(2,JJK)*HUI(JJK))))+BN(3,JJK)
	  END IF
      UN2(JJK)=CNT*DM(JJK)*1000.
      UNO3=MIN(4000.*BN(3,JJK)*DDM(JJK),UN2(JJK)-UN1(JJK))
      UNO3=MAX(0.,UNO3)
      RETURN
      END