      SUBROUTINE NYON
!     EPIC1102
!     THIS SUBPROGRAM PREDICTS DAILY ORGANIC N AND HUMUS LOSS, GIVEN
!     SOIL LOSS AND ENRICHMENT RATIO.
      USE PARM
      TOT=WHPN(LD1)+WHSN(LD1)+WBMN(LD1)+WLMN(LD1)+WLSN(LD1)
      YN=YEW*TOT
      X1=1.-YEW
      WBMN(LD1)=WBMN(LD1)*X1
      WHSN(LD1)=WHSN(LD1)*X1
      WHPN(LD1)=WHPN(LD1)*X1
      WLSN(LD1)=WLSN(LD1)*X1
      WLMN(LD1)=WLMN(LD1)*X1
      RETURN
      END