      SUBROUTINE PESTF
!     EPIC1102
!     THIS SUBPROGRAM CALCULATES THE PEST FACTOR BASED ON THE MINIMUN
!     PEST FACTOR (PST(JJK)) FOR CROP JJK AND THE SUM OF DAILY PEST
!     DAMAGE(PSTS)
      USE PARM
      IF(PSTS>0.)THEN
          X1=PSTX*PSTS/IPST
          PSTF(JJK)=1.-(1.-PST(JJK))*X1/(X1+EXP(SCRP(9,1)-SCRP(9,2)*X1))
      ELSE
          PSTF(JJK)=1.
      END IF
      RETURN
      END