      SUBROUTINE SOCIOA(IYR1,MZ,KK)
!     EPIC1102
!     THIS SUBPROGRAM OUTPUTS THE SOIL ORGANIC C AND N VARIABLES
      USE PARM
      WRITE(KW(14),30)IYR1,MZ,KK,CO2
      WRITE(KW(14),2)(SID(LORG(LID(J))),J=1,NBSL),SID(16)
      WRITE(KW(14),3)'DEPTH(m)',(Z(LID(I)),I=1,NBSL)
      WRITE(KW(14),3)'BD 33kpa(t/m3)',(BD(LID(I)),I=1,NBSL)
      WRITE(KW(14),1)'SAND(%)',(SAN(LID(I)),I=1,NBSL)
      WRITE(KW(14),1)'SILT(%)',(SIL(LID(I)),I=1,NBSL)
      WRITE(KW(14),1)'CLAY(%)',(CLA(LID(I)),I=1,NBSL)
      WRITE(KW(14),1)'ROCK(%)',(ROK(LID(I)),I=1,NBSL)
      WRITE(KW(14),1)'WLS(kg/ha)',(WLS(LID(I)),I=1,NBSL),ZLS
      WRITE(KW(14),1)'WLM(kg/ha)',(WLM(LID(I)),I=1,NBSL),ZLM
      WRITE(KW(14),1)'WLSL(kg/ha)',(WLSL(LID(I)),I=1,NBSL),ZLSL
      WRITE(KW(14),1)'WLSC(kg/ha)',(WLSC(LID(I)),I=1,NBSL),ZLSC
      WRITE(KW(14),1)'WLMC(kg/ha)',(WLMC(LID(I)),I=1,NBSL),ZLMC
      WRITE(KW(14),1)'WLSLC(kg/ha)',(WLSLC(LID(I)),I=1,NBSL),ZLSLC
      WRITE(KW(14),1)'WLSLNC(kg/ha)',(WLSLNC(LID(I)),I=1,NBSL),ZLSLNC
      WRITE(KW(14),1)'WBMC(kg/ha)',(WBMC(LID(I)),I=1,NBSL),ZBMC
      WRITE(KW(14),4)'WHSC(kg/ha)',(WHSC(LID(I)),I=1,NBSL),ZHSC
      WRITE(KW(14),4)'WHPC(kg/ha)',(WHPC(LID(I)),I=1,NBSL),ZHPC
      X1=.001*TOC
      WRITE(KW(14),4)'WOC(kg/ha)',(WOC(LID(I)),I=1,NBSL),X1
      WRITE(KW(14),1)'WLSN(kg/ha)',(WLSN(LID(I)),I=1,NBSL),ZLSN
      WRITE(KW(14),1)'WLMN(kg/ha)',(WLMN(LID(I)),I=1,NBSL),ZLMN
      WRITE(KW(14),1)'WBMN(kg/ha)',(WBMN(LID(I)),I=1,NBSL),ZBMN
      WRITE(KW(14),4)'WHSN(kg/ha)',(WHSN(LID(I)),I=1,NBSL),ZHSN
      WRITE(KW(14),4)'WHPN(kg/ha)',(WHPN(LID(I)),I=1,NBSL),ZHPN
      WRITE(KW(14),4)'WON(kg/ha)',(WON(LID(I)),I=1,NBSL),TWN
      WRITE(KW(14),4)'CFEM(kg/ha)',SMY(96)
      RETURN
    1 FORMAT(1X,A14,16F12.1)
    2 FORMAT(T52,'SOIL LAYER NO'/T18,16(4X,A4,4X))
    3 FORMAT(1X,A14,16F12.2)
    4 FORMAT(1X,A14,16F12.0)
   30 FORMAT(//T10,3I4,5X,'ATMOS CO2 =',F5.0,' ppm')
      END