      SUBROUTINE WTAIX
!     EPIC1102
!     THIS SUBPROGRAM GENERATES TMX AND TMN FOR MISSING RECORDS (999)
      USE PARM
      IF(TMX<100.)THEN
          TMN=MIN(TMNM+TNSD*WX(2),TMX-.2*ABS(TMX))
      ELSE
          TMX=MAX(TXXM+TXSD*WX(1),TMN+.2*ABS(TMN))
      END IF
      RETURN
      END